### ISSUE TITLE
Update README.md for project prep

### ISSUE THREAD

**Issue by ehilst515** [jenjones319/moonlight#7]
- [x] Upload all images from project prep 1-4
- [x] Add descriptions from preps

<hr>

Sign-offs:
 - [x] Enrique Hilst
 - [x] Jen Jones
 - [ ] Nathan Kinkade
 - [ ] Drew Scott

**Comment by ehilst515** [comment]
@jenjones319 or @nkkinkade can close this once the PR is approved

**Comment by jenjones319** [comment]
looks good.
